### ISSUE TITLE
Network Share Folders Size?

### ISSUE THREAD

**Issue by kesaribabu** [aleksaan/diskusage#16]
![server](https://user-images.githubusercontent.com/18524559/50533642-fe690f80-0b53-11e9-966c-d80afe244958.JPG)
![wmic-cmd](https://user-images.githubusercontent.com/18524559/50533643-fe690f80-0b53-11e9-97ca-7ab662963c9c.JPG)
![diskusage](https://user-images.githubusercontent.com/18524559/50533644-ff01a600-0b53-11e9-9e81-f740c9d19364.JPG)
![network](https://user-images.githubusercontent.com/18524559/50533645-ff01a600-0b53-11e9-9ace-aefe4c1071c1.JPG)

using "diskusage.exe" i get size ~44 GB
using "network share" from another PC I get ~20 GB
If I get properties directly on respective server I get ~15 GB

Could you please explain me , how exactly size is being calculated by diskusage.exe and why is that different from other two

**Comment by aleksaan** [comment]
Hi, Kesari Babu
I suppose two possibilities:
1) symlink from your disk C:\ to another disk (I see D: on your screenshot)
2) some access rights problem in diskusage and how it works with remote disk
I'm starting to test that case.

**Comment by kesaribabu** [comment]
1. Symlink? You mean Mount ? D: C: are on my PC not  on remote PC/Server for which I'm trying to get Diskusage. So, ignore D:. 

My concern was How to get Diskusage of network drives ?

**Comment by aleksaan** [comment]
kesaribabu, 
can you just test your case please

**Comment by kesaribabu** [comment]
Okay sure but I'll test it on 17th January 2019 cause I'm on vacation.

On 13-Jan-2019 4:35 AM, Alexander Anufriev <notifications@github.com> wrote:

kesaribabu,
can you just test your case please
