### ISSUE TITLE
Show all files/folders in Human-Readable mode

### ISSUE THREAD

**Issue by Prid13** [aleksaan/diskusage#35]
Just discovered this from [StackOverflow](https://stackoverflow.com/a/52008306/3705191) and I'm impressed with the speed of this versus using `dir` or `Get-ChildItem`.

However, for my use case, I simply want to print out all the files and folders in a nice table with sizes in human-friendly values (kB, MB, GB, etc.).

The `-hr` switch works great, but it cuts off the results after a certain number of rows and only shows the last row after that. Looking at the code, it's after 48 rows.

Is there a planned feature to allow for _all_ rows to be shown in `-hr` mode? It's bit a of a shame that the options are so few for what seems like a great tool :)

![image](https://user-images.githubusercontent.com/27897747/188520841-ecca7884-d73a-4da7-b601-a1f55928be49.png)

Side note: sometimes the first few letters are omitted from folders, like `ode_modules` instead of `\node_modules`. Am I doing something wrong?

**Comment by Prid13** [comment]
Upon closer inspection, why is the "Total size" showing 0? :(

**Comment by aleksaan** [comment]
> Upon closer inspection, why is the "Total size" showing 0? :(
50 rows it's limit will be printed in human readable.
>Upon closer inspection, why is the "Total size" showing 0? :(
Yes, this is bug. Thanks, try to fix near days

**Comment by aleksaan** [comment]
>> Upon closer inspection, why is the "Total size" showing 0? :(
50 rows it's limit will be printed in human readable.
>>Upon closer inspection, why is the "Total size" showing 0? :(
Yes, this is bug. Thanks, try to fix near days

**Comment by Prid13** [comment]
> And what will you do if you get 100 000 rows to console, for example? :) I can create no limit flag but it will be dangerous and unpredictable behavior. You can't look over all of these rows with your eyes, you cannot proccess these rows manually. But if you want to process these rows in another program you should't use -hr mode and get full results in json.

Maybe increase the upper limit to something like 10,000 files or 50,000 files? :)

I'll come clean and admit that my use case is different from the intended usage of this tool you've developed. I simply wish to list all the files and folders in a given directory and get a human-readable output with nice file sizes and metadata, so that I can repeatedly do this in a scheduled script to print out and save the contents of certain folders for backup and history logging purposes :)

You don't need to implement this feature. But maybe you can show me how to compile the source code after editing the limit myself for Windows? :)

**Comment by aleksaan** [comment]
@Prid13 please test new release https://github.com/aleksaan/diskusage/releases/tag/v2.9.0

**Comment by Prid13** [comment]
You're an absolute legend! This works wonderfully, and I truly appreciate you doing this so much ~⭐

I'm sorry if I caused you any inconvenience. I know this is beyond the scope of this tool, but such a feature is really handy for my use case 😇

Are there are any plans to add more options like showing creation/modification date, and sorting features? :)

------

Actually, just realized that this tool is actually a bit slow when it comes to deeply-nested folders like Documents and Downloads. I tried limiting the search by adding a `-depth 1` option, but the listing took the same amount of time regardless of using that option or not. Take e.g. my usage of this on the Downloads folder:

![image](https://user-images.githubusercontent.com/27897747/188968263-d718aac3-914e-4444-8b17-dca80a92e892.png)

![image](https://user-images.githubusercontent.com/27897747/188968369-1eaf483e-9684-4634-a561-4cca94bc019e.png)

Notice also how the total dirs, files and size remains unchanged.

The reason I discovered this is because I tried using this tool on my Documents folder, but really only want the top level (or level 2 at most) files and folders, but it was taking way too long that I thought perhaps an error was occurring for that folder. But testing it on the Downloads folder proved to me that limiting the search with a depth filter still yields the same amount of run time.

Is this the intended behavior? :O

**Comment by aleksaan** [comment]
@Prid13 Thanks for thanks
Why are times with depth and without (no depth limit) the same?
If you want to calculate size of folder you schould calculate sizes of all included subfolders and files including deepest level.
There's not previosly calculated size of folder in the file system.

And option -depth is needed only for reducing number of results rows (but it's full scan yet)

**Comment by aleksaan** [comment]
> Are there are any plans to add more options like showing creation/modification date, and sorting features?

It should be new issue. Create it please

**Comment by aleksaan** [comment]
> a bit slow when it comes to deeply-nested folders like Documents and Downloads

14000+ files (folders) per second - It's not slow I think )  And, there is some intresting fact - this program calculates size more accuracy than FAR. You can check it on c:\Users folder for example, or C:\Program Data
